services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rails_quiz_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network  # ここを追加

  web:
    build: .
    command: bash -c "until mysql -h db -u root -ppassword -e 'select 1'; do echo 'Waiting for db...'; sleep 2; done && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      RAILS_ENV: development
    networks:
      - app_network  # ここを追加

volumes:
  mysql_data:
  bundle_cache:

networks:
  app_network:  # ここを追加
    driver: bridge
