services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app_network

  web:
    build: .
    command: bash -c "until mysql -h ${DATABASE_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'select 1'; do echo 'Waiting for db...'; sleep 2; done && npm run build:css && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      RAILS_ENV: ${RAILS_ENV}
    networks:
      - app_network

volumes:
  mysql_data:
  bundle_cache:

networks:
  app_network:
    driver: bridge
