# ./config/auth0.yml
development:
  auth0_domain: "https://dev-2rxatunh2paxjn2r.us.auth0.com"
  auth0_client_id: "o69PlEX35shvRjPe9kvd0nUvhSMkXXVp"
  auth0_client_secret: "LaiACZ_HzP_1tBFi5q-6iBAtuAsZGlL9OoI-rB5lOfURxCFRJzBheV8RGEcp-X99"

